title: Austin Quillen # your name (or website title) here
logo: "images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <a href="https://mail.google.com/mail/?view=cm&fs=1&tf=1&to=arquillen@gmail.com" target="_blank"><img src="images/mailsend.png"/></a> |  
  <a href = https://my.indeed.com/p/austinq-ql0o47l"><img src="images/indeed.png"/></a> |
  <a href = https://github.com/arquillen-py"><img src="images/github.png"/>  
  <br><br>
  A place for me to keep various data science projects I've worked on. I continuously update them, so they may change from time-to-time.  
  <br><br>
  Ctrl + click on any of the badges to launch a fully interactive binder instance for each project in a new tab. They may take a bit
  to launch if they haven't been ran in a while, so please be patient; ii might take a couple minutes. You can check out a static, non-interative version
  at the repository on Github.
  <br><br>
  Feel free to email me with any questions or comments!  
  <br><br>
  E-mail: arquillen@gmail.com  
  <br>
  
theme: jekyll-theme-minimal

google_analytics: UA-204840392-1
