title: Austin Quillen # your name (or website title) here
logo: "images/logo.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)

  
  <table class="center">
  <tr>
    <td><a href="mailto:arquillen@gmail.com" target="_blank"><img src="images/mailsend.png"/></a></td>
    <td><a href = https://my.indeed.com/p/austinq-ql0o47l"><img src="images/indeed.png"/></a></td>
    <td><a href = https://github.com/arquillen-py><img src="images/github.png"/></td>
  </tr>
  </table> 
  A place where I keep various data science projects I'm working on. I continuously update them, so they may change from time-to-time.  
  <br><br>
  Ctrl + click on any of the badges to launch a fully interactive Jupyter notebook instance for each project in a new tab. They may take a bit
  to launch if they haven't been run in a while, so please be patient; it might take a few minutes. You can check out a static, non-interactive version
  by clicking the nbviewer badge.
  <br><br>
  Feel free to email me with any questions or comments!  
  <br><br>
  E-mail: arquillen@gmail.com
  <br><br>
  Location: Dayton, KY, 41074
  <br>
  <br>
  <br>
  My Badges
  <div data-iframe-width="150" data-iframe-height="270" data-share-badge-id="6f6b4303-d4d3-449a-a512-6110d64d071d" data-share-badge-host="https://www.credly.com"></div><script type="text/javascript" async src="//cdn.credly.com/assets/utilities/embed.js"></script>
  
theme: jekyll-theme-minimal

google_analytics: UA-204840392-1
